# Generated by Django 5.0.3 on 2024-03-15 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_url',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=datetime.datetime(2024, 3, 15, 7, 25, 32, 60531, tzinfo=datetime.timezone.utc), upload_to='article_images/'),
            preserve_default=False,
        ),
    ]
